let Num=()=>{

    return [
        "One",
        "Two",
        "Three",
        "Four",
        "Five",
        "Six",
        "Seven",
        "Eight",
        "Nine",
        "Ten",
        "Eleven",
        "Twelve",
        "Thirteen",
        "Fourteen",
        "Fifteen",
        "Sixteen",
        "Seventeen",
        "Eighteen",
        "Nineteen",
        "Twenty",
        "Twenty-One",
        "Twenty-Two",
        "Twenty-Three",
        "Twenty-Four",
        "Twenty-Five",
        "Twenty-Six",
        "Twenty-Seven",
        "Twenty-Eight",
        "Twenty-Nine",
        "Thirty",
        "Thirty-One",
        "Thirty-Two",
        "Thirty-Three",
        "Thirty-Four",
        "Thirty-Five",
        "Thirty-Six",
        "Thirty-Seven",
        "Thirty-Eight",
        "Thirty-Nine",
        "Forty",
        "Forty-One",
        "Forty-Two",
        "Forty-Three",
        "Forty-Four",
        "Forty-Five",
        "Forty-Six",
        "Forty-Seven",
        "Forty-Eight",
        "Forty-Nine",
        "Fifty"
      ]
      
}

export default Num()